### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Sanbbka** [RadiationX/Anilibria#1]
Привет, @RadiationX ! У вас не найдется описание API? Спасибо. 
P.S. Не охото выковыривать из исходников :)

**Comment by RadiationX** [comment]
Описания нет, только исходники

**Comment by Sanbbka** [comment]
Печально. Спасибо.

**Comment by Sanbbka** [comment]
А не подскажете, к кому можно обратиться, насчет апи?

**Comment by RadiationX** [comment]
На данный момент - только ко мне.
